[package]
name = "blockconvert"
version = "0.1.0"
authors = ["Alex Williams <hughaw64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.10", features = ["rustls-tls", "gzip", "brotli", "json"]}
futures = {version = "0.3"}
tokio = {version = "0.2", features = ["full"]}
rand = "0.7"
serde = {version = "1.0", features = ["derive"]}
lazy_static = "1.4"
async-std = "1.6"

csv = "1.1"

adblock = "0.2"
regex = "1.3"
ipnet = "2.3"

chrono = "0.4"